apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailwind-mail
  namespace: tailwind-mail
  labels:
    app.kubernetes.io/name: tailwind-mail
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: tailwind-mail.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tailwind-mail
                port:
                  name: http
