apiVersion: v1
kind: Service
metadata:
  name: tailwind-mail
  namespace: tailwind-mail
  labels:
    app.kubernetes.io/name: tailwind-mail
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tailwind-mail
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
